parameters:
    sf2gen.console.profiler_entry.class: Sf2gen\Bundle\ConsoleBundle\DataCollector\ConsoleDataCollector

services:
    sf2gen.profiler_entry:
        class: %sf2gen.console.profiler_entry.class%
        arguments: [@kernel]
        tags:
            - { name: data_collector, template: "Sf2genConsoleBundle:Console:profile.html.twig", id: "console"}